parameters:
#    ecommerce.example.class: Ecommerce\EcommerceBundle\Example

services:
    # le service de constructeur de menus. Peut servir à créer plusieurs menus
    menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    # votre menu
    menu.breadcrumb:
        class: Knp\Menu\MenuItem
        factory_service: menu_builder # le service du constructeur vu juste au-dessus
        factory_method: createBreadcrumbMenu # la méthode appelée pour générer le menu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: breadcrumb } # L'alias est utilisé dans le template